root:
  artifact: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/heydido/datasets/raw/main/CreditRiskModelingData.zip
  data_file: artifacts/data_ingestion/CreditRiskModelingData.zip
  unzip_dir: artifacts/data_ingestion
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx

data_validation:
  root_dir: artifacts/data_validation
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx
  internal_file_val_status: artifacts/data_validation/internal_file_val_status.txt
  external_file_val_status: artifacts/data_validation/external_file_val_status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  internal_raw_file: artifacts/data_ingestion/case_study1.xlsx
  external_raw_file: artifacts/data_ingestion/case_study2.xlsx
  raw_dataset: artifacts/data_ingestion/CreditRiskModelingData.csv
  preprocessed_dataset: artifacts/data_preprocessing/processed_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_dataset: artifacts/data_preprocessing/processed_data.csv
  data_transformer: artifacts/data_transformation/data_transformer.pkl

model_training:
  root_dir: artifacts/model_training
  experiment_name: XGBoostClassifier
  latest_run_id: artifacts/model_training/latest_run_id.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  latest_run_id: artifacts/model_training/latest_run_id.txt
  experiment_name: XGBoostClassifier
  train_metrics: artifacts/model_evaluation/train_metrics.txt
  test_metrics: artifacts/model_evaluation/test_metrics.txt

prediction:
  latest_run_id: artifacts/model_training/latest_run_id.txt
  experiment_name: XGBoostClassifier
  data_transformer: artifacts/data_transformation/data_transformer.pkl